# Permite que qualquer utilizador reduzir a prioridade de CPU de processos
# até -8 (niceness negativo = maior prioridade). Usado pelo Proton/Wine/Steam
# para priorizar threads de rendering e input sem necessitar de root.
* hard nice -8
* soft nice -8
