# Kernel boot parameters de hardening (derivado de secureblue)
# Instalado em /usr/lib/bootc/kargs.d/10-hardening.toml

kargs = [
  "fips=1",
  "hash_pointers=always",
  "init_on_alloc=1",
  "intel_iommu=on",
  "iommu.passthrough=0",
  "iommu.strict=1",
  "iommu=force",
  "l1d_flush=on",
  "l1tf=full,force",
  "lockdown=integrity",
  "loglevel=0",
  "mitigations=auto",
  "module.sig_enforce=1",
  "page_alloc.shuffle=1",
  "proc_mem.force_override=ptrace",
  "pti=on",
  "random.trust_bootloader=off",
  "random.trust_cpu=off",
  "randomize_kstack_offset=on",
  "rd.emergency=halt",
  "rd.shell=0",
  "slab_nomerge",
  "spec_store_bypass_disable=on",
  "spectre_v2=on",
  "ssbd=force-on",
  "systemd.ssh_auto=no",
  "vdso32=0",
  "vsyscall=none",
]
