# run with: --cap-add sys_admin --security-opt label=disable
# BASE_IMAGE      = imagem que arranca na live session (o desktop)
# INSTALL_IMAGE_PAYLOAD = imagem que o Anaconda instala no disco (pode ser a mesma)

ARG BASE_IMAGE=${BASE_IMAGE:-ghcr.io/joserenatovicente/image-fedora:latest}
ARG INSTALL_IMAGE_PAYLOAD=${INSTALL_IMAGE_PAYLOAD:-ghcr.io/joserenatovicente/image-fedora:latest}

FROM $BASE_IMAGE
ARG BASE_IMAGE
ARG INSTALL_IMAGE_PAYLOAD

RUN --mount=type=bind,source=./.,target=/src \
    env \
    BASE_IMAGE="$BASE_IMAGE" \
    INSTALL_IMAGE_PAYLOAD="$INSTALL_IMAGE_PAYLOAD" \
    /src/build.sh
